-- Question1.
-- a : 데이터베이스
-- b : DBMS
-- c : SQL


-- Question2.
-- a : COMMIT
-- b : ROLLBACK


-- Question3.
-- FROM > WHERE > GROUP BY > HAVING > SELECT > ORDER BY


-- Question4.
-- DML : INSERT, UPDATE
-- DDL : CREATE, ALTER
-- DCL : GRANT TO, REVOKE FROM


-- Question5.
-- 오류 발생 원인 : WHERE절은 출력 대상 행을 제한하고, HAVING절은 그룹화된 대상을 출력에서
-- 제한하므로 출력 결과를 제한하기 위해 HAVING을 사용하지 않고 조건식을 WHERE절에 명시하면
-- 출력 행을 제한하는 WHERE절에서는 그룹화된 데이터AVG(SALARY)를 제한하는 조건식을 지정할
-- 수 없다.
SELECT JOB_ID, AVG(SALARY) AS 평균연봉
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) > 13000
ORDER BY AVG(SALARY) DESC;


-- Question6
-- 6-1)
SELECT E.EMPLOYEE_ID, E.EMAIL, E.SALARY, D.DEPARTMENT_NAME, D.LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.SALARY >= 14000
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 6-2)
SELECT A.DEPARTMENT_ID,
       A.DEPARTMENT_NAME,
       A.MANAGER_ID,
       B.FIRST_NAME,
       B.LAST_NAME
FROM DEPARTMENTS A LEFT OUTER JOIN EMPLOYEES B
ON A.MANAGER_ID = B.EMPLOYEE_ID AND A.LOCATION_ID = 1700;


-- Question7.
SELECT FIRST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY > (
SELECT AVG(SALARY)
FROM EMPLOYEES);


-- Question8.
-- 8-1)
CREATE TABLE EMP (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2),
    CONSTRAINT EMP_EMPNO_PK PRIMARY KEY(EMPNO),
    CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES EMP(EMPNO)
);

-- 8-2)
CREATE TABLE DEPT (
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14) NOT NULL,
    LOC VARCHAR(13),
    CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY(DEPTNO)
);